// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptxrpsyvetrqickoqwgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0eHJwc3l2ZXRycWlja29xd2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5ODU1MTEsImV4cCI6MjA1MDU2MTUxMX0.uV2cHP_MRn5Ek7j2zxIwwzYt-pe-BxxfIFU8HeNWRW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);